### ISSUE TITLE
Article

### ISSUE THREAD

**Issue by IgorCavaca** [Stanimir-Ivanov/Diebold-et-al-2008-Replication#1]
Hello Staminir Ivanov.

The article you are referring to is this: "Global yield curve dynamics and interactions: A dynamic Nelson–Siegel approach" ?

**Comment by Astronautovic10** [comment]
> Hello Staminir Ivanov.
> 
> The article you are referring to is this: "Global yield curve dynamics and interactions: A dynamic Nelson–Siegel approach" ?

Hi Staminir Ivanov,

i have the same question and wanted to know which paper You are referring to, because I'm writing my thesis about yield curve modeling and wanted to implement this model as well. I checked the Code and compared it to the paper about the global yield curve from Diebold/Li/Yue from 2008. 
In the file "latent_factor_replication.R" You are performing PCA on the single country factors to get the global factors by using the 1. PCs. And I don't see this in the paper. 
So it would be awesome, if You could tell me to which paper this Code is referring :)

Kind Regards,
Olli

**Comment by Stanimir-Ivanov** [comment]
Hi both! 

Sorry for the late reply. This is indeed the "Global yield curve dynamics and interactions: A dynamic Nelson–Siegel approach" paper. Instead of deriving the hidden factors by estimating a state space model like it was done in the paper, I took a shortcut and estimated them using Principal Component Analysis. The results are quite similar. Hope this helps! 

Best,
Stanimir
